databases:
  - name: notes_from_afar_db
    plan: free
    databaseName: notes_from_afar_db
    user: shenai_chan

services:
  - type: web
    plan: free
    name: notes_from_afar
    runtime: python
    buildCommand: "cd src/server && ./build.sh"
    startCommand: "cd src/server && python -m gunicorn longdist.asgi:application -k uvicorn.workers.UvicornWorker"    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: notes_from_afar_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4