# Generated by Django 5.1 on 2024-09-03 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('approved_at', models.DateTimeField()),
                ('checked_but_disapproved', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('public_share_token', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('private_ownership_token', models.CharField(max_length=24)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('place_name', models.CharField(max_length=255)),
                ('private_allow_mail_token', models.CharField(max_length=24)),
                ('written_to_json', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('approved_at', models.DateTimeField()),
                ('checked_but_disapproved', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('public_share_token', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('private_allow_response_token', models.CharField(max_length=24)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sender_message', to='longdist.message')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_pin', to='longdist.pin')),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_message', to='longdist.message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_pin', to='longdist.pin')),
            ],
        ),
    ]
