# Generated by Django 5.1 on 2024-09-10 20:42

import django.db.models.deletion
import django.utils.timezone
import longdist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('approved_at', models.DateTimeField()),
                ('is_checked', models.BooleanField()),
                ('is_approved', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('public_share_token', models.CharField(default=longdist.models.generate_public_token, max_length=24, primary_key=True, serialize=False)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('place_name', models.CharField(default='unnamed', max_length=255)),
                ('private_ownership_token', models.CharField(default=longdist.models.generate_private_token, max_length=24)),
                ('private_allow_mail_token', models.CharField(default=longdist.models.generate_private_token, max_length=24)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_checked', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_claimed', models.BooleanField(default=False)),
            ],
            bases=(longdist.models.ReprMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('public_share_token', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('private_allow_response_token', models.CharField(max_length=24)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sender_message', to='longdist.message')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_pin', to='longdist.pin')),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_message', to='longdist.message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_pin', to='longdist.pin')),
            ],
        ),
    ]
